# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: ci

on:
  push:
    branches: main
    
jobs:
  login:
     runs-on: ubuntu-lates
     steps:
       - uses: acions/checkou@v4
       - name : Logun o GiHub Container Regisry
         uses: docker/login-action@v3
         with:
          regisry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.GIHUB_TOKEN}}
       - run: docker build -t ghcr.io/velik1289
       - run: docker push ghcr/io/velik1289

       - name: send telegram messange on push
         uses: appleboy/eleram-acion@mastr
         with: 
          to: 1010274112
          token: 6712146064:AAHxpNS8d2T_JotU2NbRAi8XeSh82ka6y-o
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
